CREATE TABLE IF NOT EXISTS student (
ID INT NOT NULL AUTO_INCREMENT,
StudentName VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS teacher (
ID INT NOT NULL AUTO_INCREMENT,
TeacherName VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS student_discount (
DiscountID INT NOT NULL AUTO_INCREMENT,
PersonID INT NOT NULL,
DiscountRate DOUBLE,
PRIMARY KEY (DiscountID),
FOREIGN KEY (PersonID) REFERENCES student(ID));

CREATE TABLE IF NOT EXISTS course (
AP BOOLEAN NOT NULL,
HONORS BOOLEAN NOT NULL,
CourseName VARCHAR(255) NOT NULL)