CREATE TABLE IF NOT EXISTS student (
id INT NOT NULL AUTO_INCREMENT,
student_name VARCHAR(255) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS teacher (
id INT NOT NULL AUTO_INCREMENT,
teacher_name VARCHAR(255) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS student_discount (
disc_id INT NOT NULL AUTO_INCREMENT,
stu_id INT NOT NULL,
disc_rate DOUBLE,
PRIMARY KEY (disc_id),
FOREIGN KEY (stu_id) REFERENCES student(id));

CREATE TABLE IF NOT EXISTS course (
ap BOOLEAN NOT NULL,
honors BOOLEAN NOT NULL,
course_name VARCHAR(255) NOT NULL)